### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by romangraef** [muolbarry/Skyblock-Dungeons-Guide#1]
I thought C young did skyblock dungons guide, why are you stealing their code go back to your own mod moulberry

**Comment by IlluminatiFish** [comment]
This is not @Moulberry, it is someone using @Moulberry's image to spread malware.

**Comment by romangraef** [comment]
but isnt malware bad? why would moulberry spread malware

**Comment by IlluminatiFish** [comment]
> but isnt malware bad? why would moulberry spread malware

Are you trolling at this point?
